### ISSUE TITLE
Complex wordpress structure case

### ISSUE THREAD

**Issue by ohmyguigs** [contentful/wordpress-exporter.rb#12]
Hi, I have a little more complex structure in wordpress that I want to export to contentful.
when running `wordpress-exporter --config-file settings.yml  --extract-to-json` the full process runs with no error, but the output is weird.
See this exemple:
This is a normal post entry
<img width="317" alt="screen shot 2017-02-22 at 14 29 40" src="https://cloud.githubusercontent.com/assets/8530905/23224022/83df43f8-f90b-11e6-98b7-f705f48a955b.png">

This another post entry, notice the category id
<img width="308" alt="screen shot 2017-02-22 at 14 31 29" src="https://cloud.githubusercontent.com/assets/8530905/23224068/a9925c2a-f90b-11e6-9d1a-54b49a653ac3.png">

Category should be an array of categories, and it is outputting an array with only one object and the "id" prop is an array of strings like `"<wp:category>\n\t\t<wp:term_id>7</wp:term_id>\n\t\t<wp:category_nicename><![CDATA[aparencia-da-loja]]></wp:category_nicename>\n\t\t<wp:category_parent><![CDATA[]]></wp:category_parent>\n\t\t<wp:cat_name><![CDATA[Aparência da Loja]]></wp:cat_name>\n\t</wp:category>",` wich should not be.

i'm not sure if i should try another approach (like using the DB exporter instead of the wordpress one)

see my exporting tool screen in wordpress:
<img width="479" alt="screen shot 2017-02-22 at 14 34 57" src="https://cloud.githubusercontent.com/assets/8530905/23224218/313a877e-f90c-11e6-9ece-d73a238e20c1.png">
I have much more fields than just posts and authors.
I did not found any info on how to deal with these more complex situations.

Thanks for the help, if it is a bug from the exporter let me know

**Comment by dlitvakb** [comment]
Hey @ohmyguigs,

This gem was thought only to solve a standard wordpress installation.

If you want to export more complicated models, you can use https://github.com/contentful/contentful-database-importer.rb

The Database Importer requires a bit more code setup, but allows arbitrarily complex data structure to be exported from your DB to Contentful.

If you need any help setting up, feel free to send a request to support@contentful.com.

Cheers

**Comment by ohmyguigs** [comment]
@dlitvakb thanks! database-importer worked like a charm! <3

**Comment by dlitvakb** [comment]
@ohmyguigs glad to hear that! 😄
